# Basic
title: Too
subtitle: Cyberjaya, Malaysia
welcome_message: Inspired By Code
description: FullStack Engineer - Game Engineer - Data Scientist
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://hitoo.co"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About, description: About, url: 'http://hitoo.co/about.html'}
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: www-hitoo-co
    # duoshuo: 
    
# Social
social:
    weibo:
    github: weiweitoo
    twitter: toosengwei1
    gplus: 
    rss: 
    mail: sengweitoo@gmail.com

